// Auto-generated by publish-to-labs.sh — DO NOT EDIT

export interface Idea {
  id: string;
  title: string;
  description: string;
  tags: string[];
  linkedItems: string[];
  createdAt: string;
  updatedAt: string;
}

export const ideas: Idea[] = [];

export function getIdeaById(id: string): Idea | undefined {
  return ideas.find((idea) => idea.id === id);
}
